config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[new create]
    end
  end

  # Create a new user with token
  post 'api/auth/sign_up', to: 'api/registration#create'
  # Generate token for an existing user
  get 'api/auth/:id', to: 'api/registration#auth'

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show] do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_save :user_token
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, length: { minimum: 1 }
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  has_many :comments, foreign_key: :author_id, dependent: :nullify
  has_many :likes, foreign_key: :author_id, dependent: :nullify
  has_many :posts, foreign_key: :author_id, dependent: :nullify

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def user_token
    update_column(:token, TokenAuthorization.jwt_encode(email))
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  # before_action :authenticate_user!
  def index
    @users = User.all

    render json: @users, status: :ok
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to new_user_session_path if current_user.nil?
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div>
  <%= link_to new_user_post_path(@user.id), class:"link-info" do %>
    <button>Create new post</button>
  <% end %>
</div>

<div class="users-container">
  <% @users.each do |user| %>
    <div class="user-container">
      <img src="<%=user.photo%>" alt="user-image" />
      <%= link_to user_path(user.id), class:"link-info" do %>
        <div class="user-info">
          <h3><%= user.name %></h3>
          <p>Number of posts: <%= user.posts.count || 0 %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
  <div class="user-container">
    <img src="<%=@user.photo%>" alt="user-image" />

    <div class="user-info">
      <h5><%= @user.name %></h5>
      <p>Number of posts : <%= @user.posts.count%> </p>
    </div>

  </div>
  <div>
    <div>
      <h5>Bio</h5>
      <p><%= @user.bio %></p>
    </div>
    <% @user.three_most_recent_posts.each do |post| %>
      <div>
        <%= link_to user_post_path(@user.id, post.id), class: "link-info" do %>
          <h4><%= post.title %></h4>
          <p><%= post.text %></p>
          <div>
            <small>Comments: <%= post.comments.count || 0 %>,</small>
            <small>Likes: <%= post.likes.count || 0 %></small>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
    <%= link_to user_posts_path(@user.id), class: "link-info" do %>
      <button>See all posts</button>
    <% end %>
  </div>
</div>