config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[new create]
    end
  end

  # Create a new user with token
  post 'api/auth/sign_up', to: 'api/registration#create'
  # Generate token for an existing user
  get 'api/auth/:id', to: 'api/registration#auth'

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show] do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_counter
  validates :title, length: { in: 1..250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :likes, dependent: :nullify
  has_many :comments, dependent: :nullify
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def five_most_recent_comments
    Comment.order(created_at: :desc).includes(:author).limit(5)
  end
end

app/controllers/api/posts_controller.rb
require_relative '../../../app/controllers/concerns/json_web_tokens'

class Api::PostsController < ApplicationController
  def index
    return unless check_auth?(params[:user_id])

    @user = User.find(params[:user_id])
    return unless @user.token?

    decoded_token = TokenAuthorization.jwt_decode(@user.token)[0]['email']
    unless decoded_token == @user.email
      render json: { error: 'Unauthorized' }, status: :unauthorized
      nil
    end
    @posts = Post.where(author_id: params[:user_id])
    render json: { success: true, data: { posts: @posts } }
  end

  private

  def check_auth?(user_id)
    user = User.where(id: user_id)
    if user.empty?
      render json: { error: 'Unauthorized' }, status: :unauthorized
      return false
    end
    true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    if current_user.nil?
      redirect_to new_user_session_path
      return
    end
    @posts = if current_user.role?
               @user.posts.includes(:comments)
             else
               @user.posts.includes(:comments, :author)
             end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    puts('life in new')
    @user = current_user
    @post = @user.posts.new
    render :new, locals: { post: @post }
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @post.destroy
    redirect_to user_post_path(@user.id, @post.id)
  end

  def create
    @user = current_user
    @add_post = Post.new(author: @user, title: post_params['title'], text: post_params['text'])
    respond_to do |format|
      format.html do
        if @add_post.save
          flash[:success] = 'Post created successfully'
          redirect_to users_path
        else
          flash.now[:error] = 'Error: Post could not be created'
          render :new, locals: { post: @add_post }
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div>
  <div class="user-container">
    <img src="<%= @user.photo %>" alt="user-image">
    <div class="user-info">
      <h3><%= @user.name %></h3>
      <p>Number of posts : <%= @user.posts.count || 0 %></p>
    </div>
  </div>
  <% @posts.each do |post| %>
    <%= link_to user_post_path(@user.id, post.id), class: "link-info" do %>
      <div>
        <%= link_to user_post_path(@user.id, post.id), class: "link-info" do %>
          <h4><%= post.title %></h4>
          <p><%= post.text %></p>
        <% end %>
      </div>
      <div>
        <small>Comments : <%= post.comments.count || 0 %></small>
        <small>Likes : <%= post.likes.count || 0 %></small>
      </div>
    <% end %>
    <% if can? :destroy, post %>
      <div><%= button_to 'Delete', user_post_path(@user.id, post.id), method: :delete %></div>
    <% end %>
    <div class="comments">
      <% post.comments.each do |comment| %>
        <p><%=comment.author.name%> : <%= comment.text %></p>
      <% end %>
    </div>
  <% end %>
  <div>
    <button>Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path(@user), method: :post, class: 'form' do |f| %>
  <div> <%= f.label :title, 'Enter post title' %><br> <%= f.text_field :title %> </div>
  <div> <%= f.label :text, 'Enter post content' %><br> <%= f.text_area :text, size: "50x6" %> </div>
  <div> <%= f.submit "Create Post" %> </div>
<% end %>

app/views/posts/show.html.erb
<div class="post-container">
  <div class="post-info">
    <div class="post-info-head">
      <h3>Post <%=@post.id %> by <%= @user.name %></h3>
      <div class="post-right-info">
        <p>Comments : <%= @post.comments.count || 0 %></p>
        <p>Likes : <%= @post.likes.count || 0 %></p>
      </div>
    </div>
    <p><%= @post.text %></p>
  </div>

  <div class="comments-info">
    <% @post.five_most_recent_comments.each do |comment| %>
      <div>
        <h6><%= comment.author.name %>: <%= comment.text %></h6>
        <% if can? :destroy, comment %>
        <div><%= button_to 'Delete', user_post_comment_path(@user.id, @post.id, comment.id), method: :delete %></div>
      <% end %>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to new_user_post_comment_path(@user, @post), class: "link-info" do %>
      <button>Add comment</button>
    <% end %>

    <%= form_with model: @like, url: user_post_likes_path(@user, @post), method: :post, class: 'form' do |f| %>
      <div> <%= f.submit "Add a like" %> </div>
    <% end %>
  </div>
</div>